# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.2' # The Go version to download (if necessary) and use.
      - name: Build for mac os 
        run: GO111MODULE=on CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build  -o ./cloner cmd/app/* 
      - name: Build for Linux
        run: GO111MODULE=on CGO_ENABLED=0 GOOS=linux go build  -o ./cloner-linux cmd/app/* 
      - name: Get release
        id: get_release
        uses: agners/get-draft-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload release binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./cloner
          asset_name: cloner-${{ steps.vars.outputs.tag }}
          asset_content_type: application/octet-stream
      - name: Upload release binary Linux
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./cloner-linux
          asset_name: cloner-${{ steps.vars.outputs.tag }}-linux
          asset_content_type: application/octet-stream
